include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: ["**/*.g.dart", "lib/core/l10n/generated/**"]
  language:
    strict-casts: true
linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    always_declare_return_types: true
